-- ALTER table Teacher
-- ADD UNIQUE(email);

DELETE FROM Teacher;

INSERT INTO Teacher (first_name, last_name, email, date_of_birth)
VALUES
	('Deborah', 'Tennant', 'deborahtennant@university.edu', '1977-5-23'::DATE),
	('Eloise', 'Mccoy', 'eloisemccoy@university.edu', '1977-2-4'::DATE),
	('Carlos', 'Henry', 'carloshenry@university.edu', '1975-12-3'::DATE),
	('Jessica', 'Washing', 'jessicawashing@university.edu', '1986-8-7'::DATE),
	('James', 'Miyoshi', 'jamesmiyoshi@university.edu', '1981-4-29'::DATE),
	('Jan', 'Smith', 'jansmith@university.edu', '1975-4-21'::DATE),
	('William', 'Ringel', 'williamringel@university.edu', '1989-5-31'::DATE),
	('Consuelo', 'Wang', 'consuelowang@university.edu', '1988-5-16'::DATE),
	('Eleanor', 'Price', 'eleanorprice@university.edu', '1990-9-13'::DATE),
	('Dorothy', 'Lenz', 'dorothylenz@university.edu', '1984-2-2'::DATE),
	('Mary', 'Flett', 'maryflett@university.edu', '1987-11-3'::DATE),
	('Sallie', 'Littleton', 'sallielittleton@university.edu', '1990-12-21'::DATE),
	('Kyle', 'Vasquez', 'kylevasquez@university.edu', '1976-8-30'::DATE),
	('Margery', 'Bohn', 'margerybohn@university.edu', '1989-2-3'::DATE),
	('Rupert', 'Miesner', 'rupertmiesner@university.edu', '1979-1-19'::DATE),
	('Sandra', 'Orozco', 'sandraorozco@university.edu', '1989-8-1'::DATE),
	('Theodore', 'Curran', 'theodorecurran@university.edu', '1990-5-15'::DATE),
	('Donald', 'Anthony', 'donaldanthony@university.edu', '1975-4-8'::DATE),
	('Doug', 'Harper', 'dougharper@university.edu', '1979-5-5'::DATE),
	('David', 'Bradley', 'davidbradley@university.edu', '1990-4-27'::DATE),
	('Chan', 'Martinez', 'chanmartinez@university.edu', '1990-12-23'::DATE),
	('Myron', 'Hamilton', 'myronhamilton@university.edu', '1986-3-15'::DATE),
	('Kelly', 'Duggins', 'kellyduggins@university.edu', '1980-4-14'::DATE),
	('Adolph', 'Boling', 'adolphboling@university.edu', '1985-10-6'::DATE),
	('Natalie', 'Peery', 'nataliepeery@university.edu', '1982-6-18'::DATE),
	('Robert', 'Luna', 'robertluna@university.edu', '1978-4-3'::DATE),
	('Kenneth', 'Sartain', 'kennethsartain@university.edu', '1980-7-18'::DATE),
	('Inge', 'Lockhart', 'ingelockhart@university.edu', '1982-11-25'::DATE),
	('Mildred', 'Green', 'mildredgreen@university.edu', '1990-5-31'::DATE),
	('Connie', 'Rooney', 'connierooney@university.edu', '1990-9-5'::DATE),
	('Houston', 'Rathbun', 'houstonrathbun@university.edu', '1989-1-17'::DATE),
	('Anthony', 'Felder', 'anthonyfelder@university.edu', '1981-1-26'::DATE),
	('Keith', 'Laman', 'keithlaman@university.edu', '1988-5-18'::DATE),
	('Arthur', 'Johnson', 'arthurjohnson@university.edu', '1984-11-11'::DATE),
	('Chris', 'Leon', 'chrisleon@university.edu', '1980-8-2'::DATE),
	('Dwight', 'Turner', 'dwightturner@university.edu', '1980-1-12'::DATE),
	('Tammy', 'Mills', 'tammymills@university.edu', '1990-1-1'::DATE),
	('Nancy', 'Harper', 'nancyharper@university.edu', '1983-2-19'::DATE),
	('David', 'Oconnor', 'davidoconnor@university.edu', '1978-5-25'::DATE),
	('Steven', 'Shewmaker', 'stevenshewmaker@university.edu', '1989-9-16'::DATE),
	('Timothy', 'Hellwig', 'timothyhellwig@university.edu', '1981-8-25'::DATE),
	('Patricia', 'Cruz', 'patriciacruz@university.edu', '1987-4-20'::DATE),
	('June', 'Sims', 'junesims@university.edu', '1980-10-3'::DATE),
	('Lynette', 'Holmes', 'lynetteholmes@university.edu', '1978-6-5'::DATE),
	('Mary', 'Perez', 'maryperez@university.edu', '1987-1-26'::DATE),
	('Nina', 'Lopez', 'ninalopez@university.edu', '1987-5-16'::DATE),
	('Camille', 'Seneker', 'camilleseneker@university.edu', '1983-7-13'::DATE),
	('Janis', 'Johnson', 'janisjohnson@university.edu', '1987-5-25'::DATE),
	('Christine', 'Stonerock', 'christinestonerock@university.edu', '1986-1-3'::DATE),
	('Robert', 'Owen', 'robertowen@university.edu', '1981-9-30'::DATE);